In [1]:
import numpy as np

In [42]:
j=[4,6,2,3,8,9]

In [43]:
d=np.array(j)

In [44]:
type(j)

list

In [45]:
j

[4, 6, 2, 3, 8, 9]

In [46]:
d

array([4, 6, 2, 3, 8, 9])

In [47]:
type(d)

numpy.ndarray

In [48]:
tuple(j)

(4, 6, 2, 3, 8, 9)

In [49]:
j

[4, 6, 2, 3, 8, 9]

In [50]:
d.shape

(6,)

In [51]:
d.ndim

1

In [52]:
s=[[4,8,90,12],[56,7,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 7, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [53]:
type(s)

list

In [54]:
arr1=np.array(s)

In [55]:
arr1

array([[ 4,  8, 90, 12],
       [56,  7, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [56]:
arr1.shape

(5, 4)

In [57]:
arr1.size

20

In [58]:
arr1.ndim

2

In [69]:
h=d.reshape(3,2)
h

array([[4, 6],
       [2, 3],
       [8, 9]])

In [62]:
d.reshape(6,1)

array([[4],
       [6],
       [2],
       [3],
       [8],
       [9]])

In [63]:
h.size

6

In [64]:
h.ndim


2

In [65]:
arr1.shape

(5, 4)

In [66]:
k=[8,4,5,84,54,58,44,54,15,17,15,16,165,235,3565,236,2652,86,286,235,35,74,5,36,25,354]

In [67]:
z=np.array(k)

In [68]:
z

array([   8,    4,    5,   84,   54,   58,   44,   54,   15,   17,   15,
         16,  165,  235, 3565,  236, 2652,   86,  286,  235,   35,   74,
          5,   36,   25,  354])

In [73]:
y=z.reshape(1,26)

In [74]:
y

array([[   8,    4,    5,   84,   54,   58,   44,   54,   15,   17,   15,
          16,  165,  235, 3565,  236, 2652,   86,  286,  235,   35,   74,
           5,   36,   25,  354]])

In [76]:
z.reshape(26,1)

array([[   8],
       [   4],
       [   5],
       [  84],
       [  54],
       [  58],
       [  44],
       [  54],
       [  15],
       [  17],
       [  15],
       [  16],
       [ 165],
       [ 235],
       [3565],
       [ 236],
       [2652],
       [  86],
       [ 286],
       [ 235],
       [  35],
       [  74],
       [   5],
       [  36],
       [  25],
       [ 354]])

In [77]:
k

[8,
 4,
 5,
 84,
 54,
 58,
 44,
 54,
 15,
 17,
 15,
 16,
 165,
 235,
 3565,
 236,
 2652,
 86,
 286,
 235,
 35,
 74,
 5,
 36,
 25,
 354]

In [79]:
list(range(3,100))

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [80]:
list(range(3,100,2))

[3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [81]:
list(range(3,100,10))

[3, 13, 23, 33, 43, 53, 63, 73, 83, 93]

In [83]:
tuple(range(3,100))

(3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99)

In [84]:
tuple(range(3,100,3))

(3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99)

In [85]:
tuple(range(3,100,10))

(3, 13, 23, 33, 43, 53, 63, 73, 83, 93)

In [86]:
list(range(-30,100))

[-30,
 -29,
 -28,
 -27,
 -26,
 -25,
 -24,
 -23,
 -22,
 -21,
 -20,
 -19,
 -18,
 -17,
 -16,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [87]:
list(range(-1,-10))

[]

In [88]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [92]:
np.arange(-1,-10,0.5)

array([], dtype=float64)

In [94]:
list(arange(-1,-10,0.5))

NameError: name 'arange' is not defined

In [99]:
for i in range(5,500,5):
    print('data',i)

data 5
data 10
data 15
data 20
data 25
data 30
data 35
data 40
data 45
data 50
data 55
data 60
data 65
data 70
data 75
data 80
data 85
data 90
data 95
data 100
data 105
data 110
data 115
data 120
data 125
data 130
data 135
data 140
data 145
data 150
data 155
data 160
data 165
data 170
data 175
data 180
data 185
data 190
data 195
data 200
data 205
data 210
data 215
data 220
data 225
data 230
data 235
data 240
data 245
data 250
data 255
data 260
data 265
data 270
data 275
data 280
data 285
data 290
data 295
data 300
data 305
data 310
data 315
data 320
data 325
data 330
data 335
data 340
data 345
data 350
data 355
data 360
data 365
data 370
data 375
data 380
data 385
data 390
data 395
data 400
data 405
data 410
data 415
data 420
data 425
data 430
data 435
data 440
data 445
data 450
data 455
data 460
data 465
data 470
data 475
data 480
data 485
data 490
data 495


In [95]:
j=[5,45,42,65,64,25,14,254,124,6,5,54,2,5]

In [96]:
j

[5, 45, 42, 65, 64, 25, 14, 254, 124, 6, 5, 54, 2, 5]

In [102]:
even = [] 
odd = [] 
for i in range(len(j)):
    if i % 2 == 0: 
        even.append(j[i]) 
    else: 
        odd.append(j[i]) 
        

In [106]:
for i in j:
    print(i)

5
45
42
65
64
25
14
254
124
6
5
54
2
5


In [103]:
even

[5, 42, 64, 14, 124, 5, 2]

In [104]:
odd

[45, 65, 25, 254, 6, 54, 5]

In [11]:
import numpy as np

In [13]:
j=[5,45,42,65,64,25,14,254,124,6,5,54,2,5]
j

[5, 45, 42, 65, 64, 25, 14, 254, 124, 6, 5, 54, 2, 5]

In [15]:
np.array([5,45,42,65,64,25,14,254,124,6,5,54,2,5])

array([  5,  45,  42,  65,  64,  25,  14, 254, 124,   6,   5,  54,   2,
         5])

In [17]:
np.mean(j)

50.714285714285715

In [19]:
np.median(j)

33.5

In [25]:
np.quantile(j,0.25)

5.25

In [31]:
r=np.random.rand(500)
r

array([6.42170127e-01, 5.01380089e-01, 7.80178265e-01, 8.91095205e-01,
       8.78163785e-01, 8.75270970e-01, 2.48678244e-01, 1.48707910e-01,
       6.19824493e-03, 8.15900645e-01, 2.19854555e-01, 1.52698532e-01,
       6.28390098e-01, 1.82121728e-01, 3.97202125e-01, 7.63621084e-01,
       3.07677341e-01, 9.30322841e-01, 6.99836508e-01, 5.96050915e-02,
       4.39682353e-01, 5.97955742e-01, 2.78454891e-01, 8.10031072e-01,
       7.25639344e-01, 7.37877365e-02, 3.94460251e-01, 4.85597365e-01,
       7.99742831e-01, 3.37535199e-01, 4.74117980e-01, 2.26346060e-01,
       4.18412684e-01, 5.15554582e-01, 2.88773013e-01, 6.56355237e-03,
       9.40629982e-01, 5.18808782e-01, 6.00436341e-01, 9.74712017e-01,
       9.50360616e-01, 1.94480963e-01, 4.04743393e-01, 8.71032106e-01,
       9.20825860e-01, 6.71971530e-01, 7.19604430e-01, 3.47434124e-01,
       5.18520527e-01, 8.25700012e-01, 9.22498556e-01, 2.86350663e-01,
       9.30625443e-01, 3.56627997e-02, 8.39642894e-01, 1.39119422e-02,
      

In [33]:
r.size

500

In [37]:
np.random.rand(50,10)

array([[3.81022109e-01, 6.74362626e-01, 6.85120337e-02, 3.10004049e-01,
        2.18594121e-01, 6.63416800e-01, 8.67734917e-01, 4.26051221e-01,
        2.35248795e-01, 4.76505144e-01],
       [4.13064440e-01, 1.51622854e-02, 8.25637598e-01, 3.43579600e-01,
        6.64613056e-03, 3.76466610e-01, 7.66215347e-01, 3.84823894e-01,
        9.05543308e-01, 4.20128857e-01],
       [3.75397872e-01, 3.66641416e-01, 2.49951825e-01, 4.70635899e-01,
        6.85852879e-01, 7.67355058e-01, 6.11084513e-01, 5.31943594e-01,
        1.73784072e-01, 6.43642235e-01],
       [6.28214032e-01, 4.05308428e-01, 1.19571883e-01, 2.41410634e-02,
        8.09096405e-01, 2.88775146e-01, 6.07073270e-01, 5.38173091e-01,
        1.68358213e-01, 2.64428059e-01],
       [5.78376613e-01, 1.01075522e-01, 2.69354144e-01, 3.52289797e-01,
        7.44100169e-01, 1.67895827e-01, 6.66120825e-01, 1.98200379e-01,
        4.27671045e-01, 1.73465867e-02],
       [4.77494132e-01, 3.80139396e-02, 6.09945761e-02, 8.80734579e-01,
   

In [39]:
np.random.randn(50,10)

array([[ 5.45043801e-01, -4.57199426e-01,  5.56993777e-01,
         1.09385989e+00,  4.29431490e-01, -7.99712506e-01,
        -1.99462160e-01, -4.05267258e-01,  2.23994017e-01,
        -5.43509452e-01],
       [ 3.74858454e-01,  2.49036085e-02, -7.68293707e-01,
         6.49235805e-01, -5.42500283e-01, -1.81847532e+00,
        -3.56340187e-01,  1.37869839e+00, -1.50211464e-01,
        -3.07531956e-01],
       [ 1.34290997e+00, -6.00777467e-02,  1.21514026e+00,
        -3.04479360e-01,  1.63330895e+00,  6.31250924e-01,
        -2.15300757e-01, -4.61296644e-01,  7.80855937e-01,
         6.67373244e-01],
       [-1.81938997e+00, -2.07881269e+00, -1.28927720e+00,
         2.07280817e+00,  2.01288096e+00, -1.21959120e-01,
         6.37493934e-01, -4.46347355e-01,  1.76562076e+00,
        -3.24974448e-01],
       [-7.91166174e-01, -2.24346308e+00,  1.65211004e+00,
        -1.63145074e+00,  1.20111334e+00, -5.66730994e-01,
        -1.83420436e+00, -7.86754770e-02, -1.17169377e+00,
         4.

In [41]:
np.random.normal(10,2,(7,4))

array([[12.56075466, 11.32324732, 11.01420568, 10.00927512],
       [10.4618137 ,  8.26593607,  9.5537705 ,  9.70619645],
       [11.46424847,  8.38938434,  5.48438813,  6.64390383],
       [ 7.07987783, 14.36888717,  8.26497501,  8.61087054],
       [ 7.6871135 , 11.6815081 , 14.34718934, 10.91997006],
       [ 9.45742969,  9.16294491,  9.03198331, 10.42430954],
       [12.92933216, 10.11121822,  7.67715654,  7.83314738]])

In [45]:
np.random.randint(35,86,200)

array([60, 82, 48, 82, 45, 37, 40, 60, 64, 45, 50, 44, 67, 65, 68, 59, 40,
       75, 49, 46, 82, 41, 50, 58, 39, 84, 48, 79, 70, 54, 80, 83, 68, 50,
       69, 45, 42, 60, 84, 85, 38, 53, 79, 71, 52, 47, 35, 73, 80, 37, 56,
       79, 67, 68, 68, 74, 58, 51, 35, 46, 79, 70, 56, 67, 53, 81, 67, 61,
       60, 52, 49, 76, 38, 70, 70, 59, 77, 49, 60, 53, 79, 61, 81, 37, 44,
       63, 79, 51, 41, 73, 70, 69, 50, 74, 62, 82, 81, 80, 59, 65, 66, 72,
       77, 42, 67, 57, 49, 51, 80, 76, 59, 67, 40, 47, 43, 76, 40, 35, 42,
       70, 64, 82, 53, 83, 73, 70, 52, 59, 46, 72, 65, 68, 80, 81, 46, 43,
       49, 37, 41, 71, 82, 49, 79, 48, 36, 44, 46, 39, 76, 82, 81, 57, 66,
       63, 65, 58, 74, 77, 38, 73, 42, 75, 39, 42, 55, 80, 58, 37, 58, 69,
       73, 38, 63, 47, 65, 46, 44, 71, 81, 36, 67, 79, 61, 75, 61, 66, 50,
       79, 68, 35, 56, 43, 81, 40, 78, 50, 55, 35, 85, 44])

In [47]:
np.random.randint(35,86,(5,5))

array([[66, 84, 70, 80, 43],
       [38, 42, 39, 51, 38],
       [85, 51, 65, 57, 38],
       [55, 72, 60, 83, 63],
       [84, 79, 67, 73, 42]])