In [1]:
import numpy as np

In [5]:
a=np.random.randint(30,99,50)
a

array([35, 91, 78, 61, 83, 41, 43, 73, 97, 42, 37, 53, 71, 76, 48, 94, 82,
       94, 80, 44, 60, 46, 65, 61, 87, 67, 84, 94, 59, 30, 65, 72, 92, 72,
       52, 58, 64, 58, 37, 45, 70, 56, 90, 37, 75, 69, 79, 72, 55, 94])

In [7]:
a[-1]

94

In [11]:
a[4]

83

In [13]:
a[19]

44

In [21]:
a[44]

75

In [9]:
import numpy as np
b=np.random.randint(10,99,(8,9))
b

array([[95, 91, 35, 22, 19, 10, 57, 64, 89],
       [21, 50, 26, 46, 15, 83, 64, 23, 37],
       [36, 86, 79, 26, 25, 37, 59, 16, 23],
       [11, 70, 87, 54, 75, 70, 15, 73, 17],
       [16, 86, 86, 85, 91, 35, 22, 88, 51],
       [20, 12, 94, 41, 50, 17, 69, 94, 77],
       [38, 11, 67, 23, 85, 73, 75, 95, 82],
       [22, 55, 86, 44, 88, 78, 62, 66, 36]])

In [19]:
b.shape

(8, 9)

In [21]:
b

array([[95, 91, 35, 22, 19, 10, 57, 64, 89],
       [21, 50, 26, 46, 15, 83, 64, 23, 37],
       [36, 86, 79, 26, 25, 37, 59, 16, 23],
       [11, 70, 87, 54, 75, 70, 15, 73, 17],
       [16, 86, 86, 85, 91, 35, 22, 88, 51],
       [20, 12, 94, 41, 50, 17, 69, 94, 77],
       [38, 11, 67, 23, 85, 73, 75, 95, 82],
       [22, 55, 86, 44, 88, 78, 62, 66, 36]])

In [23]:
b[7,0]

22

In [27]:
import pandas as pd

In [29]:
k=[4,7,2,8,7,3,90,50]
k

[4, 7, 2, 8, 7, 3, 90, 50]

In [31]:
np.array(k)

array([ 4,  7,  2,  8,  7,  3, 90, 50])

In [35]:
pd.Series(k)

0     4
1     7
2     2
3     8
4     7
5     3
6    90
7    50
dtype: int64

In [37]:
t=np.array(k)

In [39]:
t

array([ 4,  7,  2,  8,  7,  3, 90, 50])

In [47]:
t.ndim

1

In [41]:
pd.Series(k)

0     4
1     7
2     2
3     8
4     7
5     3
6    90
7    50
dtype: int64

In [45]:
pd.DataFrame(t)

0
0   4
1   7
2   2
3   8
4   7
5   3
6  90
7  50

In [59]:
db['sub'].mean90

NameError: name 'db' is not defined